version: "1.111.0"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=lissymarge@hotmail.de
      - N8N_BASIC_AUTH_PASSWORD=Sonne_Mond&Sterne_2025!n8n
     - N8N_HOST=localhost
     - N8N_PROTOCOL=http
     - WEBHOOK_URL=http://localhost:5678/
     - GENERIC_TIMEZONE=Europe/Berlin
     - N8N_ENCRYPTION_KEY=deinSichererKey


    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./affirmationen.txt:/home/node/affirmationen.txt
      - ./Arbeitsordner:/data/Arbeitsordner